spring:
  application:
    name: SpringKod

  datasource:
    url: jdbc:h2:mem:kod
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: kod
    username: admin
    password: admin
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  secret: gjhrioofgh389ur893hf87sh4r893hf89a4hywr8h4g879ah40f9h43w89zhrt398wh8rfz8h3w789tghoz8e4ti9y
  lifetime: 600000000

ml:
  url: http://localhost:8000

selectel.s3:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  endpoint: ${AWS_ENDPOINT_URL}
  region: ${AWS_REGION}
  bucket: ${AWS_BUCKET}