spring:
  application:
    name: SpringKod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1024MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

selectel.s3:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  endpoint: ${AWS_ENDPOINT_URL}
  region: ${AWS_REGION}
  bucket: ${AWS_BUCKET}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
